# https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/config.yml
baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'PaperMod'

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 5
[[menu.main]]
  name = 'Products'
  pageRef = '/products'
  weight = 5
[[menu.main]]
  name = 'Services'
  pageRef = '/services'
  weight = 5

[params]
  # Social icons may appear on your site header, footer, and other pages
  # Add as many icons as you like below
  # Icon pack "fab" includes brand icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
  # Icon pack "fas" includes solid icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
  # Icon pack "far" includes regular icons, see: https://fontawesome.com/icons?d=gallery&s=regular&m=free
  [[params.social]]
      icon      = "github" # icon name without the 'fa-'
      icon_pack = "fab"
      url       = "https://github.com/apreshill/apero"

# [params]
# homeInfoParams = [
#   { Title = "Hi there \U0001F44B", Content = 'Welcome to my blog' },
# ]

# [module]
# [[module.imports]]
#   path = 'github.com/adityatelange/hugo-PaperMod'
